### ISSUE TITLE
Flaw in the STL file for 2nd and 3rd parts

### ISSUE THREAD

**Issue by alozzy** [dalathegreat/Nissan-Leaf-Aeromod-Grille#1]
Hi Daniel,

Just a heads up that there appears to be a flaw in the model for 2of4_AeroLeafIntakeBlockerVersion1.stl and 3of4_AeroLeafIntakeBlockerVersion1.stl

![clip retainer flaws](https://user-images.githubusercontent.com/6853723/113669690-f7050a80-9668-11eb-942f-f7abb39e63a2.png)

I've circled in red the part of the retaining clip where it appears the model is missing material

**Comment by dalathegreat** [comment]
ping @Johan-92 , could you fix it? :)

**Comment by Johan-92** [comment]
> 
> 
> ping @Johan-92 , could you fix it? :)

Will do ASAP

**Comment by dalathegreat** [comment]
Massive thanks to Johan for fixing this in https://github.com/dalathegreat/Nissan-Leaf-Aeromod-Grille/pull/2
